
<?php

function add_new_users() {


    $users = [

        ["eric.abeijon@cmg.ch",  "Eric", "Abeijon"],
        ["raphael.abeille@cmg.ch",  "Raphaël", "Abeille"],
        ["sarah.albert@cmg.ch",  "Sarah", "Albert"],
        ["victor.alvarado@cmg.ch",  "Victor", "Alvarado"],
        ["eva.aroutunian@cmg.ch",  "Eva", "Aroutunian"],
        ["turgay.atamer@cmg.ch",  "Turgay", "Atamer"],
        ["mena.aviolo@cmg.ch",  "Mena", "Aviolo"],
        ["antoinette.baehler@cmg.ch",  "Antoinette", "Baehler"],
        ["mayumi.balet-kameda@cmg.ch",  "Mayumi", "Balet-Kameda"],
        ["christophe.balissat@cmg.ch",  "Christophe", "Balissat"],
        ["valerie.baenninger@cmg.ch",  "Valérie", "Banninger"],
        ["cynthia.barcellini@cmg.ch",  "Cynthia", "Barcellini"],
        ["francesco.bartoletti@cmg.ch",  "Francesco", "Bartoletti"],
        ["dominique.baud@cmg.ch",  "Dominique", "Baud"],
        ["nimrod.ben-zeev@cmg.ch",  "Nimrod", "Ben-Zeev"],
        ["noemie.bialobroda@cmg.ch",  "Noémie", "Bialobroda"],
        ["brigitte.boccadoro@cmg.ch",  "Brigitte", "Boccadoro"],
        ["sarah.boesch-sjollema@cmg.ch",  "Sara", "Boesch Sjollema"],
        ["florence.boeuf-albert@cmg.ch",  "Florence", "Boeuf-Albert"],
        ["valerie.bonnard@cmg.ch",  "Valérie", "Bonnard"],
        ["lionel.brady@cmg.ch",  "Lionel", "Brady"],
        ["pierre.burnet@cmg.ch",  "Pierre", "Burnet"],
        ["maylis.caijo@cmg.ch",  "Maÿlis", "Caijo"],
        ["maria.casaccio@cmg.ch",  "Maria", "Casaccio"],
        ["nathalie.casares@cmg.ch",  "Nathalie", "Casares"],
        ["christian.chamorel@cmg.ch",  "Christian", "Chamorel"],
        ["philippe.chanon@cmg.ch",  "Philippe", "Chanon"],
        ["genevieve.chevallier@cmg.ch",  "Geneviève", "Chevallier"],
        ["clemence.chippier@cmg.ch",  "Clémence", "Chippier-Abeijon"],
        ["corentin.clement@cmg.ch",  "Corentin", "Clément"],
        ["philippe.cohen@cmg.ch",  "Philippe", "Cohen"],
        ["valentine.collet@cmg.ch",  "Valentine", "Collet"],
        ["armelle.cordonnier@cmg.ch",  "Armelle", "Cordonnier"],
        ["diane.costoulas-jequier@cmg.ch",  "Diane", "Costoulas Jequier"],
        ["michele.courvoisier@cmg.ch",  "Michèle", "Courvoisier"],
        ["jean-christophe.crapiz@cmg.ch",  "Jean-Christophe", "Crapiz"],
        ["juan-antonio.crespillo@cmg.ch",  "Juan Antonio", "Crespillo"],
        ["diane.cros@cmg.ch",  "Diane", "Cros"],
        ["dorota.cybulska-amsler@cmg.ch",  "Dorota", "Cybulska-Amsler"],
        ["damien.darioli@cmg.ch",  "Damien", "Darioli"],
        ["jean-marc.daviet@cmg.ch",  "Jean-Marc", "Daviet"],
        ["laure-anne.dayer@cmg.ch",  "Laure-Anne", "Dayer"],
        ["isabel.de-los-angeles@cmg.ch",  "Isabel", "De Los Angeles"],
        ["eddy.debons@cmg.ch",  "Eddy", "Debons"],
        ["anne-marie.delbart@cmg.ch",  "Anne-Marie", "Delbart"],
        ["thomas.delclaud@cmg.ch",  "Thomas", "Delclaud"],
        ["clara.denzler@cmg.ch",  "Clara", "Denzler Bezencon"],
        ["claude.doriot@cmg.ch",  "Claude", "Doriot"],
        ["dominique.ducret@cmg.ch",  "Dominique", "Ducret"],
        ["francesco.d-urso@cmg.ch",  "Francesco", "D'Urso"],
        ["philippe.ehinger@cmg.ch",  "Philippe", "Ehinger"],
        ["laurent.fabre@cmg.ch",  "Laurent", "Fabre"],
        ["virginie.falquet@cmg.ch",  "Virginie", "Falquet"],
        ["brigitte.fontvielle@cmg.ch",  "Brigitte", "Fontvielle"],
        ["amelie.fourcade@cmg.ch",  "Amélie", "Fourcade"],
        ["daniel.fuchs@cmg.ch",  "Daniel", "Fuchs"],
        ["jean-valdo.galland@cmg.ch",  "Jean-Valdo", "Galland"],
        ["juliette.galstian@cmg.ch",  "Juliette", "Galstian"],
        ["claude.gastaldin@cmg.ch",  "Claude", "Gastaldin"],
        ["julien.george@cmg.ch",  "Julien", "George"],
        ["wendy.ghysels@cmg.ch",  "Wendy", "Ghysels-James"],
        ["isabelle.giraud@cmg.ch",  "Isabelle", "Giraud"],
        ["marie.golfier@cmg.ch",  "Marie", "Golfier"],
        ["mario.gomez-moreno@cmg.ch",  "Mario", "Gomez-Moreno"],
        ["jonas.grenier@cmg.ch",  "Jonas", "Grenier"],
        ["christophe.gunther@cmg.ch",  "Christophe", "Gunther"],
        ["anne.guyenot@cmg.ch",  "Anna", "Guyenot"],
        ["daniel.haefliger@cmg.ch",  "Daniel", "Haefliger"],
        ["tomas.hernandez@cmg.ch",  "Tomas", "Hernandez Bages"],
        ["alix.horngacher@cmg.ch",  "Alix", "Horngacher"],
        ["sandrine.hudry@cmg.ch",  "Sandrine", "Hudry"],
        ["gilbert.imperial@cmg.ch",  "Gilbert", "Imperial"],
        ["diego.innocenzi@cmg.ch",  "Diego", "Innocenzi"],
        ["marie-louise.jacomet@cmg.ch",  "Marie-Louise", "Jacomet"],
        ["veronique.jamain@cmg.ch",  "Véronique", "Jamain"],
        ["marjorie.jenni@cmg.ch",  "Marjorie", "Jenni"],
        ["nicolas.jequier@cmg.ch",  "Nicolas", "Jequier"],
        ["oriane.joubert@cmg.ch",  "Oriane", "Joubert"],
        ["oleg.kaskiv@cmg.ch",  "Oleg", "Kaskiv"],
        ["denitsa.kazakova@cmg.ch",  "Denitsa", "Kazakova"],
        ["adrian.kreda@cmg.ch",  "Adrian", "Kreda"],
        ["hin-keong.lam@cmg.ch",  "Hin-Keong", "Lam"],
        ["julien.lapeyre@cmg.ch",  "Julien", "Lapeyre"],
        ["francois.leclaircie@cmg.ch",  "François", "Leclaircie"],
        ["deborah.lee@cmg.ch",  "Deborah", "Lee"],
        ["angelique.leger@cmg.ch",  "Angélique", "Léger"],
        ["miaomiao.li@cmg.ch",  "Miaomiao", "Li"],
        ["gael.liardon@cmg.ch",  "Gaël", "Liardon"],
        ["edouard.liechti@cmg.ch",  "Edouard", "Liechti"],
        ["gianfranco.logiudice@cmg.ch",  "Gianfranco", "Logiudice"],
        ["jacques.maitre@cmg.ch",  "Jacques", "Maitre"],
        ["anne.malherbet@cmg.ch",  "Anne", "Malherbet"],
        ["lucie.mallet-de-chauny@cmg.ch",  "Lucie", "Mallet De Chauny"],
        ["pierre.mancinelli@cmg.ch",  "Pierre", "Mancinelli"],
        ["antoine.marguier@gmail.com", "4#y#%asc", "Antoine", "Marguier"],
        ["david.marteau@cmg.ch",  "David", "Marteau"],
        ["berangere.mathieu@cmg.ch",  "Bérangère", "Mathieu"],
        ["thierry.mertenat@cmg.ch",  "Thierry", "Mertenat"],
        ["serguei.milstein@cmg.ch",  "Serguei", "Milstein"],
        ["guillaume.moix@cmg.ch",  "Guillaume", "Moix"],
        ["juan-david.molano@cmg.ch",  "Juan David", "Molano"],
        ["isabelle.morel@cmg.ch",  "Isabelle", "Morel"],
        ["chloe.mugnier@cmg.ch",  "Chloé", "Mugnier"],
        ["domenica.musumeci@cmg.ch",  "Domenica", "Musumeci"],
        ["alessio.nebiolo@cmg.ch",  "Alessio", "Nebiolo"],
        ["raphael.nick@cmg.ch",  "Raphael", "Nick"],
        ["katherine.nikitine@cmg.ch",  "Katherine", "Nikitine"],
        ["kornelia.ogorkowna@cmg.ch",  "Kornelia", "Ogorkowna"],
        ["dimitri.papadopoulos@cmg.ch",  "Dimitri", "Papadopoulos"],
        ["jean-marie.paraire@cmg.ch",  "Jean-Marie", "Paraire"],
        ["yanna.parra-sottas@cmg.ch",  "Yana", "Parra Sottas"],
        ["antonio.pastor-otero@cmg.ch",  "Antonio", "Pastor Otero"],
        ["magali.perol-dumora@cmg.ch",  "Magali", "Perol-Dumora"],
        ["isabelle.pfeiffer@cmg.ch",  "Isabelle", "Pfeiffer"],
        ["amandine.pierson@cmg.ch",  "Amandine", "Pierson"],
        ["cecile.polin-rogg@cmg.ch",  "Cécile", "Polin-Rogg"],
        ["jeremy.prioult@cmg.ch",  "Jeremy", "Prioult"],
        ["paolo.renzi@cmg.ch",  "Paolo", "Renzi"],
        ["allison.ricca@cmg.ch",  "Allison", "Ricca"],
        ["nathalie.richard@cmg.ch",  "Nathalie", "Richard"],
        ["francoise.richard-genet@cmg.ch",  "Françoise", "Richard Genet"],
        ["florence.richez@cmg.ch",  "Florence", "Richez"],
        ["yvan.rihs@cmg.ch",  "Yvan", "Rihs"],
        ["nicolas.rinuy@cmg.ch",  "Nicolas", "Rinuy"],
        ["laurent.rochat@cmg.ch",  "Laurent", "Rochat"],
        ["carmen.rodriguez@cmg.ch",  "Carmen", "Rodriguez"],
        ["marianne.rohrbach@cmg.ch",  "Marianne", "Rohrbach"],
        ["chantal.roll@cmg.ch",  "Chantal", "Roll"],
        ["maria.rosende@cmg.ch",  "Maria", "Rosende"],
        ["yves.roth@cmg.ch",  "Yves", "Roth"],
        ["ariel.rychter@cmg.ch",  "Ariel", "Rychter"],
        ["catherine.ryser@cmg.ch",  "Catherine", "Ryser"],
        ["nicolas.salmon@cmg.ch",  "Nicolas", "Salmon"],
        ["mihail.sarbu@cmg.ch",  "Mihail", "Sarbu"],
        ["gerard.schlotz@cmg.ch",  "Gérard", "Schlotz"],
        ["marie-chantal.schlotz@cmg.ch",  "Marie-Chantal", "Schlotz"],
        ["akiko.shirogane@cmg.ch",  "Akiko", "Shirogane"],
        ["jeanne.sifferle@cmg.ch",  "Jeanne", "Sifferlé"],
        ["benedetta.simonati@cmg.ch",  "Benedetta", "Simonati"],
        ["marie-france.stalder@cmg.ch",  "Marie-France", "Stalder"],
        ["camille.stoll@cmg.ch",  "Camille", "Stoll"],
        ["francois.stride@cmg.ch",  "François", "Stride"],
        ["julie.sturzenegger-fortier@cmg.ch",  "Julie", "Sturzenegger-Fortier"],
        ["catherine.stutz@cmg.ch",  "Catherine", "Stutz"],
        ["mariama.sylla@cmg.ch",  "Mariama", "Sylla"],
        ["philippe.talec@cmg.ch",  "Philippe", "Talec"],
        ["barbara.tanquerel@cmg.ch",  "Barbara", "Tanquerel"],
        ["jacques.tchamkerten@cmg.ch",  "Jacques", "Tchamkerten"],
        ["jolanka.tchamkerten@cmg.ch",  "Jolanka", "Tchamkerten"],
        ["mladen.tcholitch@cmg.ch",  "Mladen", "Tcholitch"],
        ["ludovic.thirvaudey@cmg.ch",  "Ludovic", "Thirvaudey"],
        ["clemence.tilquin@cmg.ch",  "Clémence", "Tilquin"],
        ["nicolas.tosio@cmg.ch",  "Nicolas", "Tosio"],
        ["pascale.vachoux@cmg.ch",  "Pascale", "Vachoux"],
        ["mirela.vedeva-ruaux@cmg.ch",  "Mirella", "Vedeva Ruaux"],
        ["ilaria.vergari@cmg.ch",  "Ilaria", "Vergari"],
        ["patricia.villars@cmg.ch",  "Patricia", "Villars"],
        ["elodie.virot@cmg.ch",  "Elodie", "Virot"],
        ["jean-jacques.vuilloud@cmg.ch",  "Jean-Jacques", "Vuilloud"],
        ["stephan.wuthrich@cmg.ch",  "Stéphan", "Wuthrich"],
        ["bor.zuljan@cmg.ch",  "Bor", "Zuljan"]
    ];




    foreach ($users as $user) {
        $email = $user[0];
        $password = $user[1];
        $first_name = $user[2];
        $last_name = $user[3];

        $user_name = sanitize_title($first_name) . '.' .  sanitize_title($last_name);
        $user_id = wp_create_user($user_name, $password, $email);
        if (gettype($user_id) == 'integer') {
            wp_update_user(array('ID' => $user_id, 'first_name' => $first_name,   'last_name' => $last_name));
        }
    }
}
